apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mysql
  template:
    metadata:
      labels:
        application: mysql
    spec:
      containers:
      - name: mysql
        image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-repo:db
        volumeMounts:
        - mountPath: /data
          name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc