apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-hp
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"