apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: false
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer