apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: lab3
  labels:
    app: employees
spec:
  replicas: 2
  selector:
    matchLabels:
     app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:app
        name: webapp
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "my-sql.lab3"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: APP_COLOR
          valueFrom: 
           configMapKeyRef:
            name: webapp-config
            key: APP_COLOR